### ISSUE TITLE
Remove watch-config from the executable args

### ISSUE THREAD

**Issue by gid0** [aegershman/vector-boshrelease#18]
Hi,

I tried deploying your latest vector bosh release. No changes to the manifest, only vars.yml.

From /var/vcap/sys/log/vector/vector.stderr.log:
`error: The argument '--watch-config <watch-config>' requires a value but none was supplied

USAGE:
    vector --color <color> --config <config>... --log-format <log-format> --watch-config <watch-config>

For more information try --help`

And the vector service does not start.
After editing /var/vcap/jobs/vector/config/bpm.yml and removing the "--watch-config" arg, I can finally "monit start vector".
According to the vector --help, this arg expects a value, but none is provided. I don't think it's a manifest issue, as the template won't use any variable either in https://github.com/aegershman/vector-boshrelease/blob/main/jobs/vector/templates/config/bpm.erb.yml
I don't think this arg is useful, as config changes will be deployed by bosh, which will do a monit restart of the process. "--watch-config" is probably overkill.

**Comment by aegershman** [comment]
hey @gid0 thanks for pointing it out, I agree with you on `--watch-config`, it's not effective considering any update to `vars` which prompts a re-render of the `vector_toml` template will also prompt `monit` to restart the process. Or, at least it should.

Out of curiosity, did you configure anything for `vector_toml` in your vars.yml? Or just leave it undefined?  (for convenient links see the job spec template here: https://github.com/aegershman/vector-boshrelease/blob/edfa66c20b5042ca81e1b53d1dcd00ab62ffbaf9/jobs/vector/spec#L20 or an example I used for local development here: https://github.com/aegershman/vector-boshrelease/blob/edfa66c20b5042ca81e1b53d1dcd00ab62ffbaf9/manifests/operators/development/test-syslog-vars.yml#L1)

I'm wondering if this implies `--watch-config` has never worked. I'll test sometime in the next few days.

In the mean time I'll just remove `--watch-config` and cut a patch soon

**Comment by aegershman** [comment]
https://github.com/aegershman/vector-boshrelease/releases/tag/0.2.2

**Comment by gid0** [comment]
I used https://github.com/aegershman/vector-boshrelease/blob/edfa66c20b5042ca81e1b53d1dcd00ab62ffbaf9/manifests/operators/development/test-syslog-vars.yml as an example yes, and then it's only standard Vector config. I defined vector_toml in the vars.yml, I didn't try deploying it without this as I believe the bosh deployment would fail if the variable is not user-defined nor defined as a variable in the template.

Thank you very much for issuing a release so quick, and even more for making this bosh release!

**Comment by aegershman** [comment]
Interesting. Okay, hm, I wonder how that slipped by when I was writing this and testing earlier. That's a bit embarrassing, apologies. 

No prob, though 🤙  -- no rush but when you get a chance, try out `0.2.2` and let me know if it doesn't cooperate as expected. I'm going to mark this issue as closed in a few hours unless closed/commented otherwise, _but_, if you run into any problems please @ me in this comment body or open a new issue. Thanks for pointing this out, good catch
